services:
  backend:
    build: ./backend
    container_name: url-combinatorics-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: url-combinatorics-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
